# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bicepsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 371)
        font = QtGui.QFont()
        font.setPointSize(5)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bicepIzquierdoRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.bicepIzquierdoRadio.setGeometry(QtCore.QRect(30, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bicepIzquierdoRadio.setFont(font)
        self.bicepIzquierdoRadio.setChecked(False)
        self.bicepIzquierdoRadio.setObjectName("bicepIzquierdoRadio")
        self.bicepIzquierdoSlider = QtWidgets.QSlider(self.centralwidget)
        self.bicepIzquierdoSlider.setGeometry(QtCore.QRect(30, 60, 841, 41))
        self.bicepIzquierdoSlider.setMinimum(5)
        self.bicepIzquierdoSlider.setMaximum(165)
        self.bicepIzquierdoSlider.setPageStep(1)
        self.bicepIzquierdoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bicepIzquierdoSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bicepIzquierdoSlider.setTickInterval(5)
        self.bicepIzquierdoSlider.setObjectName("bicepIzquierdoSlider")
        self.bicepIzquierdoLabel = QtWidgets.QLabel(self.centralwidget)
        self.bicepIzquierdoLabel.setGeometry(QtCore.QRect(230, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bicepIzquierdoLabel.setFont(font)
        self.bicepIzquierdoLabel.setObjectName("bicepIzquierdoLabel")
        self.bicepDerechoSlider = QtWidgets.QSlider(self.centralwidget)
        self.bicepDerechoSlider.setGeometry(QtCore.QRect(40, 280, 841, 41))
        self.bicepDerechoSlider.setMinimum(5)
        self.bicepDerechoSlider.setMaximum(165)
        self.bicepDerechoSlider.setPageStep(1)
        self.bicepDerechoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bicepDerechoSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bicepDerechoSlider.setTickInterval(5)
        self.bicepDerechoSlider.setObjectName("bicepDerechoSlider")
        self.bicepDerechoRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.bicepDerechoRadio.setGeometry(QtCore.QRect(40, 240, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bicepDerechoRadio.setFont(font)
        self.bicepDerechoRadio.setChecked(False)
        self.bicepDerechoRadio.setObjectName("bicepDerechoRadio")
        self.bicepDerechoLabel = QtWidgets.QLabel(self.centralwidget)
        self.bicepDerechoLabel.setGeometry(QtCore.QRect(240, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bicepDerechoLabel.setFont(font)
        self.bicepDerechoLabel.setObjectName("bicepDerechoLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bicepIzquierdoRadio.setText(_translate("MainWindow", "Bicep Izquierdo"))
        self.bicepIzquierdoLabel.setText(_translate("MainWindow", "5"))
        self.bicepDerechoRadio.setText(_translate("MainWindow", "Bicep Derecho"))
        self.bicepDerechoLabel.setText(_translate("MainWindow", "5"))
