# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT_Designer_pruebas\QT_design\WidgetsRobot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dedoseleccionado=9999999
        self.distancia={0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0}
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1056, 548)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.derecha = QtWidgets.QGroupBox(self.centralwidget)
        self.derecha.setGeometry(QtCore.QRect(60, 40, 141, 171))
        self.derecha.setFlat(False)
        self.derecha.setCheckable(True)
        self.derecha.setChecked(False)
        self.derecha.setObjectName("derecha")
        self.pulgar2 = QtWidgets.QPushButton(self.derecha)
        self.pulgar2.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pulgar2.setObjectName("pulgar2")
        self.indice2 = QtWidgets.QPushButton(self.derecha)
        self.indice2.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.indice2.setObjectName("indice2")
        self.medio2 = QtWidgets.QPushButton(self.derecha)
        self.medio2.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.medio2.setObjectName("medio2")
        self.anular2 = QtWidgets.QPushButton(self.derecha)
        self.anular2.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.anular2.setObjectName("anular2")
        self.menique2 = QtWidgets.QPushButton(self.derecha)
        self.menique2.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.menique2.setObjectName("menique2")
        self.izquierda = QtWidgets.QGroupBox(self.centralwidget)
        self.izquierda.setEnabled(True)
        self.izquierda.setGeometry(QtCore.QRect(220, 40, 141, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.izquierda.setPalette(palette)
        self.izquierda.setAutoFillBackground(False)
        self.izquierda.setFlat(False)
        self.izquierda.setCheckable(True)
        self.izquierda.setChecked(False)
        self.izquierda.setObjectName("izquierda")
        self.pulgar = QtWidgets.QPushButton(self.izquierda)
        self.pulgar.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pulgar.setObjectName("pulgar")
        self.indice = QtWidgets.QPushButton(self.izquierda)
        self.indice.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.indice.setObjectName("indice")
        self.medio = QtWidgets.QPushButton(self.izquierda)
        self.medio.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.medio.setObjectName("medio")
        self.anular = QtWidgets.QPushButton(self.izquierda)
        self.anular.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.anular.setObjectName("anular")
        self.menique = QtWidgets.QPushButton(self.izquierda)
        self.menique.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.menique.setObjectName("menique")
        self.dedos = QtWidgets.QWidget(self.centralwidget)
        self.dedos.setGeometry(QtCore.QRect(390, 50, 251, 121))
        self.dedos.setObjectName("dedos")
        self.sliderdedo = QtWidgets.QSlider(self.dedos)
        self.sliderdedo.setGeometry(QtCore.QRect(40, 50, 160, 22))
        self.sliderdedo.setOrientation(QtCore.Qt.Horizontal)
        self.sliderdedo.setObjectName("sliderdedo")
        self.dedo = QtWidgets.QLabel(self.dedos)
        self.dedo.setGeometry(QtCore.QRect(100, 30, 47, 13))
        self.dedo.setObjectName("dedo")
        self.dedodistancia = QtWidgets.QLabel(self.dedos)
        self.dedodistancia.setGeometry(QtCore.QRect(100, 80, 47, 13))
        self.dedodistancia.setObjectName("dedodistancia")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
        self.pulgar.pressed.connect(self.cambiarDedo0)
        self.indice.pressed.connect(self.cambiarDedo1)
        self.medio.pressed.connect(self.cambiarDedo2)
        self.anular.pressed.connect(self.cambiarDedo3)
        self.menique.pressed.connect(self.cambiarDedo4)
        
        self.pulgar2.pressed.connect(self.cambiarDedo0_2)
        self.indice2.pressed.connect(self.cambiarDedo1_2)
        self.medio2.pressed.connect(self.cambiarDedo2_2)
        self.anular2.pressed.connect(self.cambiarDedo3_2)
        self.menique2.pressed.connect(self.cambiarDedo4_2)
        
        self.sliderdedo.valueChanged.connect(self.mover_dedos)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.derecha.setTitle(_translate("MainWindow", "Mano Derecha"))
        self.pulgar2.setText(_translate("MainWindow", "Pulgar"))
        self.indice2.setText(_translate("MainWindow", "Indice"))
        self.medio2.setText(_translate("MainWindow", "Medio"))
        self.anular2.setText(_translate("MainWindow", "Anular"))
        self.menique2.setText(_translate("MainWindow", "Menique"))
        self.izquierda.setTitle(_translate("MainWindow", "Mano Izquierda"))
        self.pulgar.setText(_translate("MainWindow", "Pulgar"))
        self.indice.setText(_translate("MainWindow", "Indice"))
        self.medio.setText(_translate("MainWindow", "Medio"))
        self.anular.setText(_translate("MainWindow", "Anular"))
        self.menique.setText(_translate("MainWindow", "Menique"))
        self.dedo.setText(_translate("MainWindow", "N/A"))
        self.dedodistancia.setText(_translate("MainWindow", "0"))

    def cambiarDedo0(self):
        self.dedo.setText("Pulgar Izquierdo")
        self.dedo.adjustSize()
        self.dedoseleccionado=0
        self.dedodistancia.setText(str(self.distancia[0]))
        self.sliderdedo.setSliderPosition(self.distancia[0])
    
    def cambiarDedo1(self):
        self.dedo.setText("Indice Izquierdo")
        self.dedo.adjustSize()
        self.dedoseleccionado=1
        self.dedodistancia.setText(str(self.distancia[1]))
        self.sliderdedo.setSliderPosition(self.distancia[1])
        
    def cambiarDedo2(self):
        self.dedo.setText("Medio Izquierdo")
        self.dedo.adjustSize()
        self.dedoseleccionado=2
        self.dedodistancia.setText(str(self.distancia[2]))
        self.sliderdedo.setSliderPosition(self.distancia[2])
        
    def cambiarDedo3(self):
        self.dedo.setText("Anular Izquierdo")
        self.dedo.adjustSize()
        self.dedoseleccionado=3
        self.dedodistancia.setText(str(self.distancia[3]))
        self.sliderdedo.setSliderPosition(self.distancia[3])
        
    def cambiarDedo4(self):
        self.dedo.setText("Menique Izquierdo")
        self.dedo.adjustSize()
        self.dedoseleccionado=4
        self.dedodistancia.setText(str(self.distancia[4]))
        self.sliderdedo.setSliderPosition(self.distancia[4])
        
        
        
    def cambiarDedo0_2(self):
        self.dedo.setText("Pulgar Derecho")
        self.dedo.adjustSize()
        self.dedoseleccionado=5
        self.dedodistancia.setText(str(self.distancia[5]))
        self.sliderdedo.setSliderPosition(self.distancia[5])
    
    def cambiarDedo1_2(self):
        self.dedo.setText("Indice Derecho")
        self.dedo.adjustSize()
        self.dedoseleccionado=6
        self.dedodistancia.setText(str(self.distancia[6]))
        self.sliderdedo.setSliderPosition(self.distancia[6])
        
    def cambiarDedo2_2(self):
        self.dedo.setText("Medio Derecho")
        self.dedo.adjustSize()
        self.dedoseleccionado=7
        self.dedodistancia.setText(str(self.distancia[7]))
        self.sliderdedo.setSliderPosition(self.distancia[7])
        
    def cambiarDedo3_2(self):
        self.dedo.setText("Anular Derecho")
        self.dedo.adjustSize()
        self.dedoseleccionado=8
        self.dedodistancia.setText(str(self.distancia[8]))
        self.sliderdedo.setSliderPosition(self.distancia[8])
        
    def cambiarDedo4_2(self):
        self.dedo.setText("Menique Derecho")
        self.dedo.adjustSize()
        self.dedoseleccionado=9
        self.dedodistancia.setText(str(self.distancia[9]))
        self.sliderdedo.setSliderPosition(self.distancia[9])

   


    def mover_dedos(self,value):
        if self.dedoseleccionado==0:
            self.dedodistancia.setText(str(value))
            self.distancia[0]=value
        if self.dedoseleccionado==1:
            self.dedodistancia.setText(str(value))
            self.distancia[1]=value
        if self.dedoseleccionado==2:
            self.dedodistancia.setText(str(value))
            self.distancia[2]=value
        if self.dedoseleccionado==3:
            self.dedodistancia.setText(str(value))
            self.distancia[3]=value
        if self.dedoseleccionado==4:
            self.dedodistancia.setText(str(value))
            self.distancia[4]=value
            
        if self.dedoseleccionado==5:
            self.dedodistancia.setText(str(value))
            self.distancia[5]=value
        if self.dedoseleccionado==6:
            self.dedodistancia.setText(str(value))
            self.distancia[6]=value
        if self.dedoseleccionado==7:
            self.dedodistancia.setText(str(value))
            self.distancia[7]=value
        if self.dedoseleccionado==8:
            self.dedodistancia.setText(str(value))
            self.distancia[8]=value
        if self.dedoseleccionado==9:
            self.dedodistancia.setText(str(value))
            self.distancia[9]=value
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
