# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cuelloGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cuello_dial = QtWidgets.QDial(self.centralwidget)
        self.cuello_dial.setGeometry(QtCore.QRect(220, 180, 361, 321))
        self.cuello_dial.setMaximum(360)
        self.cuello_dial.setPageStep(1)
        self.cuello_dial.setSliderPosition(0)
        self.cuello_dial.setTracking(True)
        self.cuello_dial.setWrapping(True)
        self.cuello_dial.setNotchTarget(3.7)
        self.cuello_dial.setNotchesVisible(True)
        self.cuello_dial.setObjectName("cuello_dial")
        self.cuello_label = QtWidgets.QLabel(self.centralwidget)
        self.cuello_label.setGeometry(QtCore.QRect(310, 60, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.cuello_label.setFont(font)
        self.cuello_label.setMouseTracking(False)
        self.cuello_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cuello_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cuello_label.setObjectName("cuello_label")
        self.label_giro_cuello = QtWidgets.QLabel(self.centralwidget)
        self.label_giro_cuello.setGeometry(QtCore.QRect(380, 520, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_giro_cuello.setFont(font)
        self.label_giro_cuello.setAlignment(QtCore.Qt.AlignCenter)
        self.label_giro_cuello.setObjectName("label_giro_cuello")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cuello_label.setText(_translate("MainWindow", "Cuello"))
        self.label_giro_cuello.setText(_translate("MainWindow", "0"))
